pipeline {
    agent any
    tools {
        maven 'maven-3.9.11'
    }
    stages {
        stage('Source') {
            steps {
                git branch: 'main',
                    changelog: false,
                    poll: false,
                    url: 'https://github.com/Tw3aky81/essential-jenkins-2468076.git'
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/Ch05/05_04-challenge-create-artifacts-and-reports"){
                    echo "Cleaning the workspace..."
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/Ch05/05_04-challenge-create-artifacts-and-reports"){
                    echo "Running tests..."
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/Ch05/05_04-challenge-create-artifacts-and-reports"){
                    echo "Creating the JAR file..."
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post {
        always {
            echo "Collecting jUnit test results..."
            junit allowEmptyResults: true, 
                testResults: '**/TEST-com.learningjenkins.AppTest.xml'

            echo "Archiving the JAR file..."
            archiveArtifacts allowEmptyArchive: true, 
                artifacts: '**/*.jar', 
                followSymlinks: false
        }
    }
}
